const Store = [
  {
    id: '1',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Dresden_Armrest%26Ottoman_ALESUND_1.jpg',
    alt: 'Image of open end sofa with armrest',
    description: 'Open End Sofa with Armrest',
    price: '$2753',
    category: ['sofa', 'featured'],
    room: 'livingroom',
  },
  {
    id: '2',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Belia_Open_End_Sofa_Chatou-Boucle_Pearl_1.jpg',
    alt: 'Image of open end sofa',
    description: 'Cloud Open End Sofa',
    price: '$2999',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '3',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Dresden_Armless_Left_Table_Plush-Weave_Oyster_1_0.jpg',
    alt: 'Image of Armless sofa with side table',
    description: 'Armless Sofa with Side Table',
    price: '$2899',
    category: ['sofa', 'trending'],
    room: 'livingroom',
  },
  {
    id: '4',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Milo_Sofa_Compact_Leuven-Linen_Opal_1.jpg',
    alt: 'Image of Compact sofa',
    description: 'Sofa - Compact',
    price: '$2100',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '5',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Milo-Sleeper-Sofa_Alesund_5.jpg',
    alt: 'Image of Sleeper sofa',
    description: 'Sleeper Sofa',
    price: '$1999',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '6',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Berlin_Sectional_Sofa_ModernFelt_Alesund_1.jpg',
    alt: 'Image of Sectional Sofa',
    description: 'Sectional Sofa',
    price: '$4099',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '7',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Berlin_L-Sectional_ModernFelt_Alesund_1.jpg',
    alt: 'Image of L-Sectional Sofa',
    description: 'L-Sectional Sofa',
    price: '$5299',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '8',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Porter_Extended_Sectional_Alesund_01.jpg',
    alt: 'Image of Extended Sectional',
    description: 'Extended Sectional',
    price: '$3299',
    category: ['sofa', 'featured'],
    room: 'livingroom',
  },
  {
    id: '9',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Evelyn_Dining_Table_71_White_Lacquered_1.jpg',
    alt: 'Image of dining table with white top',
    description: 'Evelyn Dining Table',
    price: '$1299',
    category: ['dining', 'trending'],
    room: 'diningroom',
  },
  {
    id: '10',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Tulip_Dining_Table_Oval_Carrara_1.jpg',
    alt: 'Image of Tulip Table Oval - Carrara',
    description: 'Tulip Table Oval - Carrara',
    price: '$2199',
    category: 'dining',
    room: 'diningroom',
  },
  {
    id: '11',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Winston_Rectangular_Dining_Table_1.jpg',
    alt: 'Image of Winston Rectangular Table',
    description: 'Winston Rectangular Table',
    price: '$2399',
    category: ['dining', 'featured'],
    room: 'diningroom',
  },
  {
    id: '12',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Athena_Dining_Table_Round_48in_Travertine_Alabaster_Matte_Lacquered_Base_1_0.jpg',
    alt: 'image of Athena Round Dining Table',
    description: 'Athena Round Dining Table',
    price: '$1911',
    category: ['dining', 'trending'],
    room: 'diningroom',
  },
  {
    id: '13',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Osten_Table_96_Alabaster_Lacquer_1.jpg',
    alt: 'Image of Osten Table',
    description: 'Osten Table',
    price: '$1999',
    category: 'dining',
    room: 'diningroom',
  },
  {
    id: '14',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Gallus-Dining-Table_48_Alabaster-Concrete-1.jpg',
    alt: 'Image of Gallus Dining Table',
    description: 'Gallus Dining Table',
    price: '$1779',
    category: 'dining',
    room: 'diningroom',
  },
  {
    id: '15',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Iris_Table_Lamp_Low_2_0.jpg',
    alt: 'Image of Iris Table Lamp - Low',
    description: 'Iris Table Lamp - Low',
    price: '$159',
    category: ['lighting', 'featured'],
    room: 'livingroom',
  },
  {
    id: '16',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Uma_Floor_Lamp_Mandalay-White-Marble_1.jpg',
    alt: 'Image of Uma Floor Lamp',
    description: 'Uma Floor Lamp',
    price: '$499',
    category: 'lighting',
    room: 'livingroom',
  },
  {
    id: '17',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Iris_Sconce_01.jpg',
    alt: 'Image of Iris Sconce',
    description: 'Iris Sconce',
    price: '$189',
    category: 'lighting',
    room: 'livingroom',
  },
  {
    id: '18',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Iris_Floor_Lamp_1_0.jpg',
    alt: 'Image of Iris Floor Lamp',
    description: 'Iris Floor Lamp',
    price: '$329',
    category: ['lighting', 'trending'],
    room: 'livingroom',
  },
  {
    id: '19',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Uma-Table-Lamp_White-Marble_1.jpg',
    alt: 'Image of Uma Table Lamp',
    description: 'Uma Table Lamp',
    price: '$259',
    category: 'lighting',
    room: 'livingroom',
  },
  {
    id: '20',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/BoscoFloorLamp_White_01.jpg',
    alt: 'Image of Bosco Floor Lamp',
    description: 'Bosco Floor Lamp',
    price: '$289',
    category: 'lighting',
    room: 'livingroom',
  },
  {
    id: '21',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Liza-Floor-Lamp_White_Short_1.jpg',
    alt: 'Image of Liza Floor Lamp',
    description: 'Liza Floor Lamp',
    price: '$559',
    category: 'lighting',
    room: 'livingroom',
  },
  {
    id: '22',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Aura_Floor_Lamp_Short_1.jpg',
    alt: 'Image of Aura Floor Lamp',
    description: 'Aura Floor Lamp',
    price: '$269',
    category: 'lighting',
    room: 'livingroom',
  },
  // {
  //   id: '22',
  //   img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Aura_Floor_Lamp_Short_1.jpg',
  //   alt: 'Image of Aura Floor Lamp',
  //   description: 'Aura Floor Lamp',
  //   price: '$269',
  //   category: 'lighting',
  //   room: 'livingroom',
  // },
  // {
  //   id: '22',
  //   img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Aura_Floor_Lamp_Short_1.jpg',
  //   alt: 'Image of Aura Floor Lamp',
  //   description: 'Aura Floor Lamp',
  //   price: '$269',
  //   category: 'lighting',
  //   room: 'livingroom',
  // },
  // {
  //   id: '22',
  //   img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Aura_Floor_Lamp_Short_1.jpg',
  //   alt: 'Image of Aura Floor Lamp',
  //   description: 'Aura Floor Lamp',
  //   price: '$269',
  //   category: 'lighting',
  //   room: 'livingroom',
  // },
  // {
  //   id: '22',
  //   img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Aura_Floor_Lamp_Short_1.jpg',
  //   alt: 'Image of Aura Floor Lamp',
  //   description: 'Aura Floor Lamp',
  //   price: '$269',
  //   category: 'lighting',
  //   room: 'livingroom',
  // },
];
export default Store;
