const Store = [
  {
    id: '1',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Dresden_Armrest%26Ottoman_ALESUND_1.jpg',
    alt: 'Image of open end sofa with armrest',
    description: 'Open End Sofa with Armrest',
    price: '$2753',
    category: ['sofa', 'featured'],
    room: 'livingroom',
  },
  {
    id: '2',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Belia_Open_End_Sofa_Chatou-Boucle_Pearl_1.jpg',
    alt: 'Image of open end sofa',
    description: 'Cloud Open End Sofa',
    price: '$2999',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '3',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Dresden_Armless_Left_Table_Plush-Weave_Oyster_1_0.jpg',
    alt: 'Image of Armless sofa with side table',
    description: 'Armless Sofa with Side Table',
    price: '$2899',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '4',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Milo_Sofa_Compact_Leuven-Linen_Opal_1.jpg',
    alt: 'Image of Compact sofa',
    description: 'Sofa - Compact',
    price: '$2100',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '5',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/uc_product_full/public/Milo-Sleeper-Sofa_Alesund_5.jpg',
    alt: 'Image of Sleeper sofa',
    description: 'Sleeper Sofa',
    price: '$1999',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '6',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Berlin_Sectional_Sofa_ModernFelt_Alesund_1.jpg',
    alt: 'Image of Sectional Sofa',
    description: 'Sectional Sofa',
    price: '$4099',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '7',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Berlin_L-Sectional_ModernFelt_Alesund_1.jpg',
    alt: 'Image of L-Sectional Sofa',
    description: 'L-Sectional Sofa',
    price: '$5299',
    category: ['sofa'],
    room: 'livingroom',
  },
  {
    id: '8',
    img: 'https://cdn.roveconcepts.com/sites/default/files/styles/picture_1024_2x/public/Porter_Extended_Sectional_Alesund_01.jpg',
    alt: 'Image of Extended Sectional',
    description: 'Extended Sectional',
    price: '$3299',
    category: ['sofa', 'featured'],
    room: 'livingroom',
  },
  //   {
  //     img: '',
  //     alt: '',
  //     description: '',
  //     price: '',
  //     category: '',
  //     room: '',
  //   },
  //   {
  //     img: '',
  //     alt: '',
  //     description: '',
  //     price: '',
  //     category: '',
  //     room: '',
  //   },
  //   {
  //     img: '',
  //     alt: '',
  //     description: '',
  //     price: '',
  //     category: '',
  //     room: '',
  //   },
  //   {
  //     img: '',
  //     alt: '',
  //     description: '',
  //     price: '',
  //     category: '',
  //     room: '',
  //   },
  //   {
  //     img: '',
  //     alt: '',
  //     description: '',
  //     price: '',
  //     category: '',
  //     room: '',
  //   },
  //   {
  //     img: '',
  //     alt: '',
  //     description: '',
  //     price: '',
  //     category: '',
  //     room: '',
  //   },
];
export default Store;
